services:
  app:
    container_name: memowave
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3300:3300"
    environment:
      NODE_ENV: development
